{{- if .Values.sso.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "technitium-dns-server.ssoClientSecretName" . }}
  labels:
    {{- include "technitium-dns-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.sso.clientSecret | quote }}
{{- end }}
